changelog:
  exclude:
    labels:
      - ignore-for-release
      - duplicate
      - question
      - invalid
      - wontfix
    authors:
      - dependabot

  categories:
    - title: 新機能 / New Features
      labels:
        - feature
        - enhancement

    - title: バグ修正 / Bug Fixes
      labels:
        - fix
        - bugfix
        - bug

    - title: ドキュメント / Documentation
      labels:
        - documentation
        - docs

    - title: その他の変更 / Other Changes
      labels:
        - chore
        - refactor
        - style
        - test
        - ci
        - build
        - perf

    - title: 破壊的変更 / Breaking Changes
      labels:
        - breaking-change
        - breaking
